### ISSUE TITLE
React group project: Kanban board set up

### ISSUE THREAD

**Issue by agneta1991** [agneta1991/space-traveller#25]
# Within this issue we would like to share our Kanban board set up:

- We have created an empty repo
- Copied the template (react group project)
- As it is 2 of us in the group, we have deleted all the tasks for the 3d member.
- We have assigned ourselves to the tasks.

https://github.com/agneta1991/Space-traveller/projects/1

The collaboration is between Agneta Pupienyte & Ochieng Steven Otieno

**Comment by Cabraham1** [comment]
Hi @agneta1991 @Ochiengsteven  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
